autoKill:
  ACACIA_DOOR_ITEM: 1
  ACACIA_FENCE: 1
  ACACIA_FENCE_GATE: 1
  ACACIA_STAIRS: 1
  ACTIVATOR_RAIL: 1
  AIR: 1
  ANVIL: 1
  APPLE: 1
  ARMOR_STAND: 1
  ARROW: 1
autoHarvest:
  ACACIA_DOOR_ITEM: 1
  ACACIA_FENCE: 1
  ACACIA_FENCE_GATE: 1
  ACACIA_STAIRS: 1
  ACTIVATOR_RAIL: 1
  AIR: 1
  ANVIL: 1
  APPLE: 1
  ARMOR_STAND: 1
  ARROW: 1
autoCollect:
  ACACIA_DOOR_ITEM: 1
  ACACIA_FENCE: 1
  ACACIA_FENCE_GATE: 1
  ACACIA_STAIRS: 1
  ACTIVATOR_RAIL: 1
  AIR: 1
  ANVIL: 1
  APPLE: 1
  ARMOR_STAND: 1
  ARROW: 1